/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterAdminRouteImport } from './routes/registerAdmin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupTrackedProjectsRouteImport } from './routes/setup/tracked-projects'
import { Route as SetupClockifyRouteImport } from './routes/setup/clockify'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAdminRoute = RegisterAdminRouteImport.update({
  id: '/registerAdmin',
  path: '/registerAdmin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTrackedProjectsRoute = SetupTrackedProjectsRouteImport.update({
  id: '/setup/tracked-projects',
  path: '/setup/tracked-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupClockifyRoute = SetupClockifyRouteImport.update({
  id: '/setup/clockify',
  path: '/setup/clockify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registerAdmin': typeof RegisterAdminRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/setup/clockify': typeof SetupClockifyRoute
  '/setup/tracked-projects': typeof SetupTrackedProjectsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registerAdmin': typeof RegisterAdminRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/setup/clockify': typeof SetupClockifyRoute
  '/setup/tracked-projects': typeof SetupTrackedProjectsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registerAdmin': typeof RegisterAdminRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/setup/clockify': typeof SetupClockifyRoute
  '/setup/tracked-projects': typeof SetupTrackedProjectsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registerAdmin'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/setup/clockify'
    | '/setup/tracked-projects'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registerAdmin'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/setup/clockify'
    | '/setup/tracked-projects'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/registerAdmin'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/setup/clockify'
    | '/setup/tracked-projects'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterAdminRoute: typeof RegisterAdminRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SetupClockifyRoute: typeof SetupClockifyRoute
  SetupTrackedProjectsRoute: typeof SetupTrackedProjectsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registerAdmin': {
      id: '/registerAdmin'
      path: '/registerAdmin'
      fullPath: '/registerAdmin'
      preLoaderRoute: typeof RegisterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/tracked-projects': {
      id: '/setup/tracked-projects'
      path: '/setup/tracked-projects'
      fullPath: '/setup/tracked-projects'
      preLoaderRoute: typeof SetupTrackedProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/clockify': {
      id: '/setup/clockify'
      path: '/setup/clockify'
      fullPath: '/setup/clockify'
      preLoaderRoute: typeof SetupClockifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterAdminRoute: RegisterAdminRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SetupClockifyRoute: SetupClockifyRoute,
  SetupTrackedProjectsRoute: SetupTrackedProjectsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
